//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacs_user
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string sex { get; set; }
        public string identityno { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string deptid { get; set; }
        public string deptname { get; set; }
        public string venderid { get; set; }
        public string vendername { get; set; }
        public string ischecked { get; set; }
        public string remark { get; set; }
        public string createdate { get; set; }
        public string createtime { get; set; }
        public string createuser { get; set; }
        public string updatedate { get; set; }
        public string updatetime { get; set; }
        public string updateuser { get; set; }
        public string delflag { get; set; }
        public string ip { get; set; }
    }
}
