//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacs_log
    {
        public string log_type { get; set; }
        public string create_date { get; set; }
        public string create_time { get; set; }
        public string create_ip { get; set; }
        public string create_user { get; set; }
    }
}
