//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacs_role
    {
        public string id { get; set; }
        public string name { get; set; }
        public string remark { get; set; }
        public string createdate { get; set; }
        public string createtime { get; set; }
        public string createuser { get; set; }
        public string updatedate { get; set; }
        public string updatetime { get; set; }
        public string updateuser { get; set; }
        public string delflag { get; set; }
    }
}
